name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        ruby: ['2.7', '3.0', 'head']
    steps:
      - uses: actions/checkout@v2
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run:  bundle install
      - name: Run tests
        run:  bundle exec rake spec
